### ISSUE TITLE
add support to use wire1?

### ISSUE THREAD

**Issue by yanzixiang** [blemasle/arduino-mcp23017#2]
the library use WRIE default ?
but some board have two i2c-bus or more,
how to use another i2c-bus?

**Comment by blemasle** [comment]
Hi @yanzixiang . Would you have an example of such boards so I can have a look at it ? I've never used one myself.

**Comment by yanzixiang** [comment]
@blemasle 
i use this.
https://github.com/espressif/arduino-esp32
