### ISSUE TITLE
ESP8266/ESP32 Support

### ISSUE THREAD

**Issue by openedhardware** [blemasle/arduino-mcp23017#20]
Just curious if this library is capable with ESP8266/ESP32?

**Comment by blemasle** [comment]
Hi,

I can't see a reason why it would not work. I don't have an ESP32 at hand though, so I encourage you to test it and report it here 🙂

**Comment by marcow1601** [comment]
I have successfully used the library with an ESP8266 before, don't see any reason why it shouldn't work either. :)
