### ISSUE TITLE
Datasheet Change Due To Issue Discovered In MCP23017 Chip

### ISSUE THREAD

**Issue by woolseyj** [blemasle/arduino-mcp23017#33]
I found out today that Microchip discovered an [issue](https://microchip.my.site.com/s/article/GPA7---GPB7-Cannot-Be-Used-as-Inputs-In-MCP23017) in their MCP23017 chip where under certain circumstances the I2C SDA signal may become corrupted when the chip’s GPA7 and/or GPB7 pins are used as inputs.  For this reason, they updated the [datasheet](https://ww1.microchip.com/downloads/aemDocuments/documents/APID/ProductDocuments/DataSheets/MCP23017-Data-Sheet-DS20001952.pdf) to reflect that those pins should only be used as outputs.

I'm hopeful that a silicon revision is in the works, but I wanted to alert the library maintainer in case they were unaware of the issue.

**Comment by blemasle** [comment]
Hi,

Sorry this notification slipped out of my mind. I was not aware of that issue, thanks.
I'll update the readme to include a warning regarding those pins.

Thanks again.
